#PD revisited
planar_2dof:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joints_position_controller:
    type: my_controller_unit5/PositionController
    joint1: joint1
    joint2: joint2
    omega: [10.0]