#PID Unit 2
planar_2dof:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joints_position_controller:
    type: my_controller_unit3_traj_int/PositionController
    joint1: joint1
    joint2: joint2
    gains1: [333.42,66.67] #PD
    gains2: [333.42,66.67] #PD
    coef1_a: [0.0,0.0,0.01178097,-0.0003927] #a0,a1,a2,a3 link1
    coef2_a: [1.48352986,0.0,-0.00850848,0.00028362] #a0,a1,a2,a3 link1